export const ROUTES = {
  HOME: '/',
  HALLS: '/halls',
  HALL_DETAILS: (id: string) => `/halls/${id}`,
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  SIGNUP: '/register',
  ACCOUNT: '/account',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_BOOKINGS: '/account/bookings',
  ACCOUNT_BOOKING_DETAILS: (id: string) => `/account/bookings/${id}`,
  ACCOUNT_FAVORITES: '/account/favorites',
  ACCOUNT_REVIEWS: '/account/reviews',
  ACCOUNT_SETTINGS: '/account/settings',
  MY_BOOKINGS: '/my-bookings',
  BOOKING_DETAILS: (id: string) => `/bookings/${id}`,
  CHECKOUT: (id: string) => `/bookings/${id}/checkout`,
  VENDOR_DASHBOARD: '/vendor/dashboard',
  VENDOR_HALLS: '/vendor/halls',
  CREATE_HALL: '/vendor/halls/create',
  EDIT_HALL: (id: string) => `/vendor/halls/${id}/edit`,
  ADMIN_DASHBOARD: '/admin/dashboard',
} as const;
